### PR TITLE
Jacob's Contest Timer

### PR DESCRIPTION
**Pull request by isabelcoolaf**
This pull request adds a Jacob's Contest timer and fixes a couple bugs with the timers in general.
The contest reminder is sent 20 minutes after the Dark Auction reminder was sent.

I fixed the callEveryHour method to use `setTimeout` instead of `setInterval` because this was causing the bot to spam messages to the server. (Hypixel's anti-spam caught it previously)
I also fixed the fact that the first reminders would not go until after an hour of runtime.

Also yes I tested this on my own server it took hours and it works fine.

### CODE REVIEW

**Comment by Sychic** [comment]
Perhaps we could just combine the jacob's event with the da timer?

**Comment by isabelcoolaf** [comment]
If people could keep track of 20 minutes lmao
Otherwise it's a highly requested feature.

**Comment by Sychic** [comment]
> 
> 
> If people could keep track of 20 minutes lmao
> Otherwise it's a highly requested feature.

I mean combine the code so it just counts additionally from the da timer

**Comment by isabelcoolaf** [comment]
That's... how i did it

**Comment by Sychic** [comment]
ok trying to read the code with literally only the changes is too confusing

**Pull request merged**
